# Site settings
title: FileKit
description: FileKit is a Swift framework that allows for simple and expressive file management.
url: "https://nvzqz.github.io"
baseurl: "/FileKit"
author: Nikolai Vazquez
twitter_username: nikolaivazquez
github_username:  nvzqz

# Build settings
markdown: kramdown
